spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=quartz
    username: postgres
    password: postgres
  jpa:
      hibernate:
        ddlAuto: none
server:
  port: 8082



